name = "aikizi-api"
main = "src/worker/index.ts"
compatibility_date = "2024-09-25"
account_id = "10caedbcfcc1e6179107cde83789ac60"

[vars]
# keep comma-separated, no spaces needed
CORS_ORIGIN = "https://aikizi.xyz,https://aikizi.com,http://localhost:5173"
AI_PROVIDER = "gemini" # or "openai"
# Admin user IDs (Supabase auth.users.id UUIDs) for /v1/debug/auth access
# Format: comma-separated list, e.g., "uuid1,uuid2,uuid3"
ADMIN_USER_IDS = ""

# JWKS Configuration (REQUIRED for JWT verification with asymmetric keys)
# SUPABASE_JWKS_URL = "https://<PROJECT_REF>.supabase.co/auth/v1/.well-known/jwks.json"
# SUPABASE_JWT_ISSUER = "https://<PROJECT_REF>.supabase.co/auth/v1"

# Secret bindings (set via: wrangler secret put <NAME>)
# - SUPABASE_URL
# - SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_KEY
# - SUPABASE_JWKS_URL
# - SUPABASE_JWT_ISSUER
# - CF_IMAGES_ACCOUNT_ID
# - CF_IMAGES_TOKEN
# - GEMINI_API_KEY
# - SREF_ENCRYPTION_KEY
# - CRON_SECRET

# Let Wrangler manage your zone route
[[routes]]
pattern = "aikizi.xyz/v1/*"
zone_name = "aikizi.xyz"

# Keep .com commented until transfer day
# [[routes]]
# pattern = "aikizi.com/v1/*"
# zone_name = "aikizi.com"

[triggers]
crons = ["0 0 * * *"]
