name = "aikizi-api"
main = "src/worker/index.ts"
compatibility_date = "2024-09-25"

[vars]
CORS_ORIGIN = "https://aikizi.xyz,https://aikizi.com,http://localhost:5173"

[[routes]]
pattern = "aikizi.xyz/v1/*"
zone_name = "aikizi.xyz"

# (keep this block commented until the .com moves to your main CF account)
# [[routes]]
# pattern = "aikizi.com/v1/*"
# zone_name = "aikizi.com"
